version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
    - dbvolume1:/var/lib/postgresql/data/pgdata
    ports:
    - "5432"
  redis:
    image: redis
  web:
    build:
      context: .
      args:
        # Use the DB that the postgres container already has
        DATABASE_URL: postgres://postgres:postgres@db/postgres
    ports:
    - "8000:8000"
    depends_on:
    - db
    - redis
volumes:
  dbvolume1: {}
