apiVersion: v1
kind: Service
metadata:
  name: opendebates
  labels:
    app: opendebates
spec:
  type: LoadBalancer
  ports:
  - name: "default"
    port: 80
    targetPort: 8000
  selector:
    app: opendebates
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opendebates
spec:
  selector:
    matchLabels:
      app: opendebates
  replicas: 2
  template:
    metadata:
      labels:
        app: opendebates
    spec:
      containers:
      - image: docker.io/dpoirier/opendebates:latest
        imagePullPolicy: Always
        name: opendebates
        ports:
        - containerPort: 8000
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: DATABASE_URL
            value: postgres://postgres:postgres@db/postgres
