apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pci-opendebates-testing-redis2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
#  storageClassName: do-block-storage
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - image: redis
        name: redis
        resources: {}
        volumeMounts:
          - mountPath: /data
            name: redisvolume
      restartPolicy: Always
      volumes:
        - name: redisvolume
          persistentVolumeClaim:
            claimName: pci-opendebates-testing-redis2
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
