# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-27 12:54
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opendebates', '0001_squashed_0041_auto_20170331_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='search_index',
        ),
        migrations.AddField(
            model_name='submission',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=django.contrib.postgres.indexes.GinIndex(fields=[b'search_vector'], name='opendebates_search__dd5129_gin'),
        ),
    ]
