# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opendebates', '0003_populate_submission_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flag',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='opendebates.Submission'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='opendebates.Submission'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='original_merged_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes_merged_elsewhere', to='opendebates.Submission'),
        ),
    ]
